#docker-compose.yml(compose-spec.json)

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./db_data:/var/lib/postgresql/data:rw" 
    ports:
      - "5432:5432"
    networks: 
      - airflow
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin 
  #   ports:
  #     - "8081:80"
  #   networks: 
  #     - airflow

networks:
  airflow:
    external:
      name: airflow_default
